### ISSUE TITLE
[MVP 2] Auth

### ISSUE THREAD

**Issue by amyamyx** [amyamyx/Slack-c#12]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
  - [x] Add `cursor: pointer` all your buttons and navlinks!
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by xnanodax** [comment]
I unchecked 2 boxes above. Demo login + random route

**Comment by xnanodax** [comment]
Awesome! demo login works!

**Comment by amyamyx** [comment]
Demo login and random route fixed!
